### ISSUE TITLE
how to use iOpenValueHelp and iChangeEditingStatus

### ISSUE THREAD

**Issue by seimon-ohh** [ui5-community/wdi5#274]
Hi all,
i´m trying to use the method iOpenValueHelp from the sap.fe.test api. https://sapui5.hana.ondemand.com/#/api/sap.fe.test.api.FilterBarActions%23methods/iOpenValueHelp
The parameter "vFieldIdentifier" is required but i dont know whats expected for that. How do i identify explicit fields?

I also want to use the method iChangeEditingStatus.
https://sapui5.hana.ondemand.com/#/api/sap.fe.test.api.FilterBarActions%23methods/iChangeEditingStatus
The required parameter is "sEditState" which should be an enum out of these: https://sapui5.hana.ondemand.com/#/api/sap.fe.test.api.EditState%23overview
My question is also here: How should the parameter look like, or rather, how do I access the enums?

BR Simon

**Comment by vobu** [comment]
that's definitely something for @Siolto or @georgbischoff, as it's their daily (testing) business 😄 → guys, please jump in and help @seimon-ohh

**Comment by georgbischoff** [comment]
Hi Simon,

1. The expected syntax for **ChangeFilterField** is: `When.onTheMainPage.iChangeFilterField({ property: "OverallStatus" },"O")`. In the code example OverallStatus is the name of a field. In most cases you should find the name of the property in the related entityset of your metadata.
2. In case of **iChangeEditingStatus** you typically refer to sap.fe.test.api.EditState in an OPA5 Journey. In WDI5 you can also directly pass the state in uppercase, e.g. ALL or UNCHANGED.
Code example: `When.onTheMainPage.onFilterBar().iChangeEditingStatus("UNCHANGED")`

Regards,
Georg

**Comment by ARiesterer** [comment]
Hi Simon,
in many of the sap.fe.test.api test-functions you can pass the "vFieldIdentifier" parameter as either an object or as a string.
In case of an object you have to pass the (internal) name of the field you can find in the metadata (as described by Georg already). In case of a string, you can pass the content of the label of that field on the UI. 
In case of FilterBarActions.iOpenValueHelp() this would be the label content of the parameter field of the action dialog you want to open the value help for.
Passing the content of a label is a bit more critical than passing the internal name because the same label might be existing more than once on the UI which would mean that the test is executed for every label content found on the UI.
Regards
Andreas
