### ISSUE TITLE
Test failing to find expand header button

### ISSUE THREAD

**Issue by sebage** [ui5-community/wdi5#333]
Hi,

we face the issue that for one of our apps the expand header button can not be found. It is using a DynamicPage with a SmartFilterbar in the DynamicPage header and a Title in the DynamicPageTitle.

Expanded header:
![image](https://user-images.githubusercontent.com/99413677/186418122-b6e7ab87-b4dd-4fec-8019-2f0d148c5d8c.png)

Collapsed header:
![image](https://user-images.githubusercontent.com/99413677/186418183-744cc87b-5541-4831-af55-17108df17288.png)

The strange thing is that this issue only occurs on a certain execution environment. 
We have two cloud spaces on which we test the apps. They host exactly the same app. We execute them with SAP internal test automation tool STEP. This creates a container to run the tests. 

Testing the app on space A is always successful (executed locally or via STEP)
Testing the app on space B it always fails to find the expand button when the tests are executed with STEP. Executing the same test locally from my notebook it works without any issue.

This issue started last Saturday, there was no change on our app or the tests. Not sure if there was any change within STEP. 
STEP should always have the same environment as listed below. And our app should also be the same on both spaces.

We have a second app with the same structure and there we don't face this issue.

Do you have any idea what could causing this issue or how to further investigate such a case?

**Selector used**
```
    {
        forceSelect: true,
        selector: {
            controlType: "sap.m.Button",
            viewName: sEventMasterViewName,
            properties: {
                    icon: "sap-icon://slim-arrow-down"
            }
    }
    }
```

initially we had the following selector, but it shows the same issue:
```
    {
    	selector: {
            controlType: "sap.ui.core.Icon",
            viewName: sEventMasterViewName,
            properties: {
                    src: {
                            regex: {
                                    source: "slim\\-arrow\\-down"
                            }
                    }
            }
        }
    }
```

**Logs/Console Output**
As the log is quite long and has some sensitive information i have extracted the relevant parts:
[shortened_log.txt](https://github.com/ui5-community/wdi5/files/9416051/shortened_log.txt)

As we see a timeout in the logs, i already tried to extend it to 30 seconds in the WDI5 config, but this didn't help.

**Runtime Env :**
WDI5: 0.9.10
UI5: 1.105.0
chrome: 102.0.5005.115
chromedriver: 102.0.5005.61
os: Linux 5.10.123-garden-cloud-amd64 x86_64
node: 14.19.3
wdio: 7.23.0

**Comment by Siolto** [comment]
Hi @sebage,

thanks for the detailed description and also your log. As I have never worked with STEP before, I can not tell if the issue is on the STEP side or not. But looking at your log the following lines caught my eye:

```bash
[0-2] message: 'Error: Polling stopped because the timeout of 15000 milliseconds has been reached but there is still pending asynchronous work.\n' +
```
Event though you already tried to increase the timeout I think that something in your application is loading very slowly and is causing your issue.

wdi5 is synchronized with the ui5 framework. For that we use the same polling mechanism that OPA5 is using. As long as some asynchronous work is not done yet (i.e. unfinished backend requests or the application itself has not loaded completely) wdi5 will not start with the actual localization of the controls. 
The default timeout for that is 15 seconds. You can increase that timeout with following property in the wdi5 configuration:

```javascript
wdi5: {
    waitForUI5Timeout: 45000 // 45 seconds
}
```
When you increase the timeout higher than 30 seconds you also have to increase following timeout in your `spec` file as well otherwise the wdi5 internals will run into problems:
```javascript
await browser.setTimeout({ 'script': 45000 })
```

If you still face some issues after increasing the timeout drastically you could send me maybe a condensed log where the `logLevel` of `wdio` and `wdi5` is set to `error`.

I hope this will help you to solve your issue

Best regards,
Simon

**Comment by sebage** [comment]
Hi @Siolto,

thanks for the quick response.

I increased the timeout to 90000, but the error was still occuring. This time it was another control that is not found, the header title (for the SmartFilterBar we expect that it does not exist when the header is collapsed):

[0-2] [31m[wdi5][0m call of _getControl() failed because of: Error: waitAsync is already running and cannot be called again at this moment
[0-2] [31m[wdi5][0m error retrieving control: batchSmartFilterBarcomsap.scn.mt.MTEventUI.view.Mastersap.ui.comp.smartfilterbar.SmartFilterBar
[0-2] [31m[wdi5][0m call of _getControl() failed because of: Error: waitAsync is already running and cannot be called again at this moment
**[0-2] [31m[wdi5][0m error retrieving control: mPageTitlecomsap.scn.EventUI.view.Master
[0-2] [31m[wdi5][0m Can not call "getText", because control could not be found**
[0-2] Error in "Product Batches Masterpage Filter tests.should collaps the header"
Error: expect(received).toBe(expected) // Object.is equality

Expected: "Product Batches"
Received: undefined

As you have mentioned it could be related to the app loading, i moved all the tests related to the header expanding / collapsing to the end of our spec file.
Since then the test was running successful several times. I will monitor it the next days and give an update in case it fails again.

**Comment by Siolto** [comment]
Hi @sebage,

good that you could fix your "issue" by moving the tests at a later point. Bad that the root cause of that is still not clear.

### Regarding your error in the console you shared:
This error you are now seeing in the console (`waitAsync is already running and cannot be called again at this moment`) are now the wdi5 internals that run into problems due to the high timeout. You have to add following line at the beginning of your test script (best case would be in the before hook) to resolve that:
```javascript
before(async () => {
        await browser.setTimeout({ 'script': 45000 }) // it has to be as high as the 'waitForUI5Timeout'
    })
```

Regards,
Simon

**Comment by sebage** [comment]
Hi @Siolto,

i had the following statement in the first it-block of the affected spec file when getting the error shown in the log:
`await browser.setTimeout({ 'script': 90000 })`

Does it make a difference to add it to before()? If yes, i can try this as well.

Best Regards,

Sebastian

**Comment by Siolto** [comment]
Hi @sebage,

that should work. The only other timeout I am aware of that could have an affect here is the mocha/jasmine timeout. You could increase that in your `wdio.conf.js` as well.

```javascript
 mochaOpts: {
        ui: "bdd",
        timeout: 60000
    },
```

**Comment by sebage** [comment]
Hi @Siolto,

thanks for the information. 

Recently the issue did not occur anymore, without changing anything from our side. Hence i will close the ticket, if the issue occurs again i will let you know.

Best Regards,

Sebastian
