### ISSUE TITLE
Reopen Issue 257

### ISSUE THREAD

**Issue by malkoto1** [ui5-community/wdi5#390]
https://github.com/ui5-community/wdi5/issues/257
#257

**Comment by dominikfeininger** [comment]
https://github.com/ui5-community/wdi5/issues/257#issuecomment-1135520142

**Comment by dominikfeininger** [comment]
Hi, sry for the delay. Had a glance into your example. Thanks for providing the code.

Unfortunately it is like expected. See the screenshot. It is a UI5 "Bug". The `getAggregation("rows")` call returns the three rows with `id: "__row0-container-testCalendarApp---idAppControl--PC1-1" (console). But the actual DomId is: `__row0-container-testCalendarApp---idAppControl--PC1-1-CLI` note the postfix `-CLI`. So wdio is not able to retrieve the DOM part of the control. 

This should be fixed on UI5 side. Until then I will provide a working solution like we did with the `sap.m.Combobox`. Please give me some days. To speed things up you are very welcome to integrate your PlanningCalendar test into the wdi5 example on a new page/ route. Since the most effort is to provide the test/ testcase and the required example in the sample app.
See How to contribute: https://js-soft.github.io/wdi5/#/contributing 

![Screenshot 2022-05-24 at 09 32 31](https://user-images.githubusercontent.com/4546829/169974895-aa57db75-b1ab-4440-b570-d801566451d8.png)

**Comment by QA-ler** [comment]
Hello together, 

I faced a similar error using getAggregation("items") of a sap.m.List see:
![IssueInAsControlFunction](https://user-images.githubusercontent.com/121550022/209798386-23a53257-a109-4c99-b2c3-f84848038c2d.png)

The element which is used is a sap.m.CustomListItem and also has a postfix("-trigger" in this case). 
It always uses the same element, if that helps you.

The ID of the selector and the wdio_ui5_key are correct, but _domId is not.

**Comment by dominikfeininger** [comment]
> Hello together,
> 
> I faced a similar error using getAggregation("items") of a sap.m.List see: ![IssueInAsControlFunction](https://user-images.githubusercontent.com/121550022/209798386-23a53257-a109-4c99-b2c3-f84848038c2d.png)
> 
> The element which is used is a sap.m.CustomListItem and also has a postfix("-trigger" in this case). It always uses the same element, if that helps you.
> 
> The ID of the selector and the wdio_ui5_key are correct, but _domId is not.

Hi, this might be solved by adding `interaction: "root"` to the selector. See https://github.com/ui5-community/wdi5/blob/78091e884bdd6b5cb1972dd28c6ea40b0ac948a3/examples/ui5-js-app/webapp/test/e2e/aggregation.test.js#L21

**Comment by dominikfeininger** [comment]
Hi @malkoto1,

please check example test here: https://github.com/ui5-community/wdi5/blob/feature/planningCalendar/examples/ui5-js-app/webapp/test/e2e/planningCalendar.test.js

https://github.com/ui5-community/wdi5/pull/395 

I tried to comment all the doges. Which  indicates the API just works litte different.

**Comment by QA-ler** [comment]
> Hi, this might be solved by adding `interaction: "root"` to the selector. See
> 
> https://github.com/ui5-community/wdi5/blob/78091e884bdd6b5cb1972dd28c6ea40b0ac948a3/examples/ui5-js-app/webapp/test/e2e/aggregation.test.js#L21

Hi @dominikfeininger,

With your information, I have now also found it in the docs. Therefore, sorry for the writing in this issue.
Works just fine. Thanks a lot!
