### ISSUE TITLE
browser.asControl({timeout ... has no effect

### ISSUE THREAD

**Issue by nair-sumesh** [ui5-community/wdi5#392]
**Describe the bug**
For a slow responding systems where the page takes too much time to respond, the ```timeout``` feature of the **browser.asControl** has no affect.

**To Reproduce**
Not possible to  reproduce on every system.

**Expected behavior**
The timeout parameter should respect the wait for the element to load.

**Logs/Console Output**

*Code*
```js
     await browser.asControl({
      selector: {
        controlType: 'sap.ushell.ui.launchpad.AnchorItem',
        properties: { "title":"Administrator" }
      },
      timeout: 90000,
      forceSelect: true
    })
 
```

*Output*
![image](https://user-images.githubusercontent.com/12034160/208524333-96a9aa4d-e176-414b-abc3-5b52faec5472.png)

**Screenshots**
if applicable, add screenshots to help explain your problem.

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 1.0.3
- `UI5` version: 1.106.1
- `wdio`-version (output of `wdio --version`): 7.195
- `node`-version (output of `node --version`): 18.12.1
- OS: MacOS
- Browser + Version 1.108

**Comment by nair-sumesh** [comment]
### Further Observation
##### sap.ui.test.autowaiter._autoWaiter
Config being passed to ```extendConfig``` has no defined name
![image](https://user-images.githubusercontent.com/12034160/208689400-18ebde50-78e8-4de1-9bda-2d92878bcf4c.png)

Available list of waiters are as follows
![image](https://user-images.githubusercontent.com/12034160/208690032-e0446d66-1928-45be-a32a-8456c416d612.png)

As per my analysis, the timeout is not added to any waiters.

**Comment by dominikfeininger** [comment]
Hi @nair-sumesh 

in https://github.com/ui5-community/wdi5/blob/main/client-side-js/getControl.js https://sapui5.hana.ondemand.com/sdk/#/api/sap.ui.test.RecordReplay%23methods/sap.ui.test.RecordReplay.waitForUI5 to apply the custom timeout.

which was enhanced here: https://github.com/ui5-community/wdi5/blob/78091e884bdd6b5cb1972dd28c6ea40b0ac948a3/client-side-js/injectUI5.js#L51

I found some occurrences of `waitForUI5` where the enhancement was not used (`_getAggregation`, `_navTo`). Would like to clarify this first @edvardas-kireilis  @vobu

**Comment by vobu** [comment]
ping, still valid

**Comment by Siolto** [comment]
After having a hard time debugging this, I may have found the Bug:

It is not our custom `timeout` on the selector but the synchronization with the ui5 framework through `sap/ui/test/autowaiter/_autoWaiterAsync`. That's why I want to bring @hmanchev in the loop.

It seems like the `sap/ui/test/autowaiter/_autoWaiterAsync` is not feature complete or a little bit flaky with some requests. For example all requests via [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/fetch) are not recognized and will not be awaited till they are resolved/rejected.

Also the request fired via [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest) which are not specifically marked as `async` will be also not correctly tracked.

Further investigation is needed to really find the root of this problem.

**Comment by hmanchev** [comment]
Hi colleagues, 

OPA experts are notified about this potential bug and we are waiting for their feedback. Please stay tuned. 

BR,
Hristo

**Comment by kineticjs** [comment]
Hi @nair-sumesh, @dominikfeininger ,

Can we please clarify the expected behavior again:
After checking the code, I see that the timeout parameter of [sap.ui.test.RecordReplay.waitForUI5 ](https://openui5nightly.hana.ondemand.com/api/sap.ui.test.RecordReplay#methods/sap.ui.test.RecordReplay.waitForUI5) has the following role: prevents the waitForUI5 function from waiting 'forever' i.e. stops the waiting after reaching the given timeout value (even if the app still has pending/unfinished tasks)

I'm linking a snippet that demonstrates it:

the snippet schedules a task to be executed after 900ms, 
but at the same time sets a wait timeout of 800ms 
=> the waiting stops before the task is done

Steps:
-- open https://jsbin.com/kigotohuko/1/edit?html,js,output
-- press the "waitforUI5" button
=> an alert "Polling stopped because the timeout of 800 milliseconds has been reached but there is still pending asynchronous work." is displayed BEFORE the alert with "async task is done"

Locally I also simulated the same setup but with a long-running task (>90000ms) with the same result

**So, if we are on the same page, did you mean that in your setup the waitForUI5 kept waiting event after the timeout passed?**

**Comment by kineticjs** [comment]
A side note regarding the observation of @nair-sumesh that the timeout value was not passed to the individual waiters. It looked like bug to me too initially, however I checked that it does not affect the processing since the individual waiters do not need to know that 'timeout' value. 
The [custom] timeout is handled on a different level, see:
![customTimeout](https://user-images.githubusercontent.com/8408297/216580112-75544851-2974-4f15-a8a5-923d6b9f1f7d.png)
so it is still applied

**Comment by Siolto** [comment]
Hi @kineticjs 

thanks for looking into this issue. Yes in your example everything is working as expected. But as already written above, it is not about the `setTimeout` but more about `fetch` or `xmlHttpRequest` requests which are not correctly covered via the `waitForUI5`. Maybe there are even more cases that are not covered by the autoWaiter but these are the two examples I could find.

I have a minimal reproducible example for you with a running express server:

- clone https://github.com/Siolto/waitForUI5
- run `npm install`
- run `npm run start:ui5` and `npm run start:node` in two different terminals
- click on one of the buttons you will see that:
      - `setTimeout` <== works
      - `fetch` <== does not work
      - `xmlHttpRequest` <== only works with `async` specifically set to `true` (example is in the [code](https://github.com/Siolto/waitForUI5/blob/e117864999f12941636055f15c60d484639658cf/webapp/autoWait.js#L47))

For the `xmlHttpRequest` I may have found the [line](https://github.com/SAP/openui5/blob/9624921c2a35778e3a548d0edeaf4a49bfa4301c/src/sap.ui.core/src/sap/ui/test/autowaiter/_XHRWaiter.js#L109) where you could start debugging. It seems like there is the bug.

For the `fetch` I am pretty sure this should be handled via [_promiseWaiter.js](https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/test/autowaiter/_promiseWaiter.js) but there is to much 🪄 going on to give you a concrete guidance here.

I hope my example helps you get to the root of this problem.

Regards
Simon

**Comment by nair-sumesh** [comment]
> Hi @Siolto,
> 
> 
> 
> Thank you the samples that clearly show cases not covered by the auto-waiter. I'll request internally to plan a research why these were not covered so far and discuss their inclusion. 
> 
> 
> 
> I posted my earlier question because these two cases (fetch and sync xmlHttpRequest) are examples where the auto-waiter **does not wait at all** (because it does not even **detect** them), while the original issue was supposedly about the auto-waiter **waiting too long** (because @nair-sumesh mentioned the auto-waiter did not respect the custom timeout)
> 
> 
> 
> This is why I wanted @nair-sumesh to clarify again the original issue (waiting too long  OR not waiting enough time). 

@kineticjs: It's the case of not waiting enough time. As mentioned in this thread, this happens only for few UI5 controls.     
One of the cases, when the automation does not wait, is for the menu items or the tiles on the welcome page of FLP.    
As you can see from my original example, the auto-waiter is not waiting for at least 90 seconds for the menu 'Administrator' to appear, before concluding the 'No dom element found using the control selector'.


Regards,
Sumesh Nair

**Comment by kineticjs** [comment]
Hi @nair-sumesh,

>"the auto-waiter is not waiting for at least 90 seconds for the menu 'Administrator' to appear"

I see... I re-checked that the timeout parameter does not instruct the auto-waiter how long to wait. The auto-waiter waits until it no longer detects ongoing async operations in the app, If those operations complete earlier than the timeout, the auto-waiter will stop waiting. Only if the operations take longer than the timeout, the auto-waiter will stop (because **the role of the timeout is only to prevent the auto-waiter become stuck waiting**...)

So @Siolto suggested that maybe the auto-waiter exits earlier because it cannot detect some ongoing async operations in the app, because the auto-waiter does not detect requests that use the _fetch_ native API or _xmlHttpRequest_ without _async_ set to _true_  @nair-sumesh, do you know if your app initiates such requests?
I searched for usages of  the _fetch_ native API in the Core UI5 framework and couldn't find any (there is a centralized sap/base/util/fetch module that uses XMLHttpRequest underneath). The sync requests are considered legacy so I expect they are also no longer in use...

In all cases I'd suggest that we need to reproduce the actual issue in question (if we can get access to the app) to be certain we are tracing the issue in the app and not another potential issue...

**Comment by kineticjs** [comment]
After discussion we planned to enhance the auto-waiter with support for fetch and sync xmlHttpRequest. Thanks again @Siolto  for taking the time to compose the clear samples. We will update when the new implementation is available.

**Comment by kineticjs** [comment]
Hi @nair-sumesh,

Just as a side note, I see you are using UI5 version 1.106.1 which does not contain a recent enhancement to the auto-waiter https://github.com/SAP/openui5/commit/6b478630a249a8311ab1e77fe29efb7111ac55da that enables it to track ongoing animations. It was included in 1.107 and all later UI5 versions.
Given that  1.106 is no longer listed as supported (I'm checking against the list  at https://sapui5.hana.ondemand.com/versionoverview.html) you could (if you want) from now update to 1.108 or any later supported version while we are working on the remaining discussed enhancements (tracking of _fetch_ and _XMLHttpRequest_ without _async_ set to _true_)

**Comment by nair-sumesh** [comment]
👀

**Comment by vobu** [comment]
hey @nair-sumesh , the latest version should contain a fix for that. could you please test-drive? thanks!

**Comment by nair-sumesh** [comment]
blocker  #473
