### ISSUE TITLE
All .asControl() calls fails if the application uses sap.ui.vk library

### ISSUE THREAD

**Issue by ilya-antonets** [ui5-community/wdi5#429]
If the application uses `sap.ui.vk` library, any `.asControl()` call performed after loading a 3D scene fails with `waitAsync is already running and cannot be called again at this moment` error.

The reason is that the `sap.ui.test.autowater._autoWaiter` waits for any callbacks passed to `window.requestAnimationFrame()` method to be executed. However, `sap.ui.vk` uses this method continuously for rendering 3D content so the `autoWaiter` will always timeout.

wdi5 should provide an ability to configure the set of waiters used by `waitAsync` so they could be enabled or disabled during the test execution.

Ideally, `sap.ui.test.autowaiter._jsAnimationWaiter` should ignore callbacks originated from `sap.ui.vk` library.

**Comment by vobu** [comment]
thanks for both describing the erroneous behavior and for digging deep for the root cause 👍 
Given that for the lifecycle sync with UI5, we try to remain as close to the standard `autowaiter` as possible (and so just reuse it), I'd refrain at this time from any custom manipulation of its' behavior.
Having said that, @kineticjs and colleagues are already enhancing the `autowaiter`, b/c we found it is currently not taking `fetch` and sync `xhr` calls into account. So pining the colleagues (also @jdichev) here so they're aware of the effects you described.
My hope would be that your finding gets resolved within the enhanced `autowaiter` implementation. If not, we'll try (together with you, ja?!? 😸) to bolt in configurable waiters and/or an ignore patterns from `sap.ui.vk`.

**Comment by vobu** [comment]
hey @kineticjs - just leaving a ping here to inquire if the above issue is on your radar? 😁
