### ISSUE TITLE
No Suggestion items shown for sap.m.input field

### ISSUE THREAD

**Issue by Pravalika-Gandesiri** [ui5-community/wdi5#436]
Hi, 
I am currently working on SAP UI5 project and need to write WDI5 tests for the same. 

**Test Scenario:**
We have a sap.m.input control in our UI which gives the Suggestion list on entering n characters. 

**Problem:**
In WDI5 test, the suggestion list is not shown even after giving the text in the input control. 

**Code Snippet:**
_const inputControl= await browser.asControl({
            selector: { 
               id: "myTestId",
               controlType: "sap.m.input", 
           } 
       }); 
 await inputControl.enterText("Testdata");_

**Comment by vobu** [comment]
this is the same root cause as #355 
short recap: missing functionality in the record replay API of UI5; UI5 colleagues are working on it.
mitigation for the time being would be to manually send `return` à la (pidgeon code)
```js
await inputControl.focus()
await browser.keys("Return") // or send `constants.Return` https://github.com/webdriverio/webdriverio/blob/e78ecef891b2de4a2f7c198117d35db8debf1c68/packages/webdriverio/src/constants.ts#L325
```

**Comment by Dhanushadoor** [comment]
Hi @vobu,

I really appreciate your speedy response.
We're following up on the reference issue which you mentioned.

The workaround you have suggested doesn't seem to work, since our requirement is dependent on the Suggestion list.
It's crucial to click on the suggestion to carry forward with the test scenario.

Please let us know if there are any other ways to achieve the same!

Kind Regards,
Dhanush
