### ISSUE TITLE
EmptyQue error coming from OPA5 is not handled correctly.

### ISSUE THREAD

**Issue by Harcsa95** [ui5-community/wdi5#448]
**Describe the bug**
While running multiple actions inside of a fiori elements facade, we're getting an error on the console log, which makes the tests fail, even though the steps are executed successfully.
Error message:
`Cannot read property 'stack' of null`

This is coming from [testFrameworkFnWrapper](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/src/test-framework/testFnWrapper.ts#L76), because there the incoming error should have a stack property, and the incoming `null` obviously doesn't have that. This results in the error  `Cannot read property 'stack' of null`.

This is thrown from [wdi5-fe](https://github.com/ui5-community/wdi5/blob/main/src/lib/wdi5-fe.ts#L54), here the error is already `null`, not checked here, only the fact that it is an error.

After some debugging, we've identified, that the error(`null`) is coming from: 
[testLibrary](https://github.com/ui5-community/wdi5/blob/main/client-side-js/testLibrary.js#L52) `emptyQueue` method

This error is thrown from the `sap/ui/test/Opa5.js` in the `emptyQueue` function.
This is a simle js Error here, but on the consuming side, it is expected, that the catched error has an `errorMessage` property.

It seems, that that the `Opa5.js` is throwing the error because it is somehow called multiple times simultaneously.

Unfortunately we cannot share the spec here, but here is the excerpt of it:
```js
let fioriElementsFacade =  await browser.fe.initialize(facadeConfig); // this contains a list report and an object page
await fioriElementsFacade.execute(async (Given, When, Then) => {
  await When.onTheDetailPage.iGoToSection("tableWithPropertyX");
  await When.onTheDetailPage.onTable({ property: "X" }).iExecuteCreate();
  await When.onTheDetailPage.onTable({ property: "X" }).iChangeRow(
      0, { "property": "value" }
  );
 //here it's more consistently reproducable if at least 5 rows are added to the table
  await When.onTheDetailPage.iGoToSection("tableWithPropertyY");
  await When.onTheDetailPage.onTable({ property: "Y" }).iExecuteCreate();
  await When.onTheDetailPage.onTable({ property: "Y" }).iChangeRow(
      0, { "property": "value" }
  );
  await When.onTheDetailPage.onFooter().iExecuteSave();
});
```
Somewhere along the Proerty Y create/change/save the mentioned error is thrown.

**To Reproduce**
Unfortunately I don't know how to reproduce this without our spec, but you can give me a call any time within SAP, for a quick demo.

**Expected behavior**
Since the required steps are executed as expected, I would expect that no error makes the spec fail. (If we directly modify the [testFnWrapper](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/src/test-framework/testFnWrapper.ts#L76) to check that the `err` is null, then the spec executes successfully.)

**Logs/Console Output**
`Cannot read property 'stack' of null`

**Screenshots**
Unfortunately cannot paste any here.

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 1.3.1
- `UI5` version: 1.108.9
- `wdio`-version (output of `wdio --version`): 6.0.1
- `node`-version (output of `node --version`): v18.14.2
- OS: MacOS Ventura 13.2.1
- Browser + Version: Chrome 111.0.5563.64

**Additional context**
Test runs both in CI environment, there it's running with --headless, both also reproducible if it runs locally(however locally it's not that consistent).

Thanks in advance:
Harcsa-Pinter, Balint

**Comment by Siolto** [comment]
Hi @Harcsa95,

thanks for debugging this issue that far! You are already deep down in the FE lib rabbit hole 😄. As you already mentioned it seems like this is very hard to reproduce especially because opa5 is also involved. I would ping you in the next few days to get to the root of the problem together.

Regards,
Simon

**Comment by metzing** [comment]
Hi @Siolto, thanks! Please include me in the internal discussion as well.

**Comment by metzing** [comment]
One thing I found on further investigation is that on the WDI5 side, the `emptyQueue` function of `client-side-js/testLibrary.js` **is not** called mutliple times, however in the browser it does appear multiple times in VMs. The exact invocation **is** coming from WDI5 though, because any modification to that file is also reflected in the VMs. The call stack starts at  some file seemingly by the Chromium team, so I suspect it is `chromedriver`-related code. It seems though that the issue is not on the OPA5 side

@Siolto if you could help investigate further it would be much appreciated. This is still hindering our adoption of WDI5 as the issue is reproduced by many specs across two projects.

**Comment by Siolto** [comment]
Hi @metzing sorry for the long delay. I am again on it!

**Comment by Siolto** [comment]
@metzing @Harcsa95,

finally understood the issue! It is the [script timeout](https://webdriver.io/docs/timeouts/#session-script-timeout) which makes the execution problematic. In short, the individual steps within the execute function take too long (which is why it occurs more frequently in the pipeline).

How can you fix this:

1. Upgrade to the latest `wdi5` version. And increase the `waitForUI5Timeout` until the error no longer occurs (probably something around 60 seconds)  We already made [improvements](https://github.com/ui5-community/wdi5/blob/de120fb292d097ff712ff01f6a3bab4d58ccee68/src/service.ts#L28) with the script timeout but this will not solve all of your problems

A real fix is on the way 😄 

Regards,
Simon
