### ISSUE TITLE
How reload a browser with multiremote

### ISSUE THREAD

**Issue by thuyboehm** [ui5-community/wdi5#451]
We use multiremote to make our tests with different user roles. It is necessary to reload the browser to see the changes of the other users.

For example:
User2 make some changes in browserInstance2
User1 are able to see the changes from User2 in browserInstance1 <- but the browser needs to be reload.

With `browserInstance1.url("#");` it is possible to updated only the url for one browser instance, but this do not trigger the reload of the website. The result is that browserInstance1 is not able to see the changes from browserInstance2.

Is there an other way to realize the workflow?

**Comment by vobu** [comment]
hi, if it were me, i'd naïvely try browserInstance.refresh()  https://v7.webdriver.io/docs/api/webdriver#refresh - mind that you will need to re-inject wdi5 afterwards again à la https://ui5-community.github.io/wdi5/#/configuration?id=skipinjectui5onstart

**Comment by sangeeta298** [comment]
Hi, our setup is slightly more complicated. In addition to multi remote, we are also using btp and custom authentications. If we add skipInjectUI5OnStart: true in wdi5 config then we get below error:

[0-0] [wdi5] skipped wdi5 injection!
[0-0] 2023-04-20T15:11:25.414Z ERROR webdriver: Request failed with status 500 due to javascript error: javascript error: Cannot read properties of undefined (reading 'waitForUI5Options')
[0-0] JavaScript stack:
[0-0] TypeError: Cannot read properties of undefined (reading 'waitForUI5Options')
[0-0]     at eval (eval at executeAsyncScript (:553:26), <anonymous>:4:65)
[0-0]     at eval (eval at executeAsyncScript (:553:26), <anonymous>:33:8)
[0-0]     at eval (eval at executeAsyncScript (:553:26), <anonymous>:33:33)
[0-0]     at executeAsyncScript (<anonymous>:553:47)
[0-0]     at apply.logging (<anonymous>:568:29)
[0-0]     at callFunction (<anonymous>:447:22)
[0-0]     at <anonymous>:461:23
[0-0]     at <anonymous>:462:3
[0-0]   (Session info: headless chrome=112.0.5615.137)
JavaScript stack:
TypeError: Cannot read properties of undefined (reading 'waitForUI5Options')
    at eval (eval at executeAsyncScript (:553:26), <anonymous>:4:65)
    at eval (eval at executeAsyncScript (:553:26), <anonymous>:33:8)
    at eval (eval at executeAsyncScript (:553:26), <anonymous>:33:33)
    at executeAsyncScript (<anonymous>:553:47)
    at apply.logging (<anonymous>:568:29)
    at callFunction (<anonymous>:447:22)
    at <anonymous>:461:23
    at <anonymous>:462:3
  (Session info: headless chrome=112.0.5615.137)
    at async clientSide_getControl (/node_modules/wdio-ui5-service/client-side-js/getControl.js:3:12)

If we comment out skipInjectUI5OnStart: true and refresh using await browserInstance.refresh(); we receive error:
Error: waitUntil condition timed out after 60000ms
    at listOnTimeout (internal/timers.js:526:9)
    at processTimers (internal/timers.js:500:7)
    at async Promise.all (index 1)

**Comment by sangeeta298** [comment]
Hi,
Also tried:
await browserInstance.refresh();
await ui5Service.injectUI5(browserInstance);

and received error: 
[MultiremoteBrowser #0-0] Cannot read property 'wdi5' of undefined
[MultiremoteBrowser #0-0] TypeError: Cannot read property 'wdi5' of undefined
[MultiremoteBrowser #0-0]     at /Users/d052977/git/flex-e2e/node_modules/wdio-ui5-service/dist/lib/wdi5-bridge.js:235:48
[MultiremoteBrowser #0-0]     at step (/Users/d052977/git/flex-e2e/node_modules/wdio-ui5-service/dist/lib/wdi5-bridge.js:56:23)
[MultiremoteBrowser #0-0]     at Object.next (/Users/d052977/git/flex-e2e/node_modules/wdio-ui5-service/dist/lib/wdi5-bridge.js:37:53)
[MultiremoteBrowser #0-0]     at /Users/d052977/git/flex-e2e/node_modules/wdio-ui5-service/dist/lib/wdi5-bridge.js:31:71
[MultiremoteBrowser #0-0]     at new Promise (<anonymous>)
[MultiremoteBrowser #0-0]     at __awaiter (/Users/d052977/git/flex-e2e/node_modules/wdio-ui5-service/dist/lib/wdi5-bridge.js:27:12)
[MultiremoteBrowser #0-0]     at injectUI5 (/Users/d052977/git/flex-e2e/node_modules/wdio-ui5-service/dist/lib/wdi5-bridge.js:230:12)
[MultiremoteBrowser #0-0]     at Service.<anonymous> (/Users/d052977/git/flex-e2e/node_modules/wdio-ui5-service/dist/service.js:154:74)
[MultiremoteBrowser #0-0]     at step (/Users/d052977/git/flex-e2e/node_modules/wdio-ui5-service/dist/service.js:33:23)
[MultiremoteBrowser #0-0]     at Object.next (/Users/d052977/git/flex-e2e/node_modules/wdio-ui5-service/dist/service.js:14:53)

While debugging, in wdio-ui5-service -> service.js -> injectUI5, both this._config and browserInstance.config are undefined.
Line 153 config = this._config ? this._config : browserInstance.config;

**Comment by vobu** [comment]
this is still interesting...once bandwidth is there, we'll include it in our test suite

**Comment by dominikfeininger** [comment]
@sangeeta298 can you please provide some feedback about the provided suggestion.

**Comment by thuyboehm** [comment]
Hi @vobu, hi @dominikfeininger,

is there any update on this issue?

**Comment by vobu** [comment]
someone still needs to try this out :)

**Comment by thuyboehm** [comment]
Hi @vobu ,

Sangeeta wrote at Mai 2023, that she try this out:
await browserInstance.refresh();
await ui5Service.injectUI5(browserInstance);
But this do not working because of some error.

Maybe can you please help what should we try out?

Thanks

**Comment by vobu** [comment]
> Sangeeta wrote at Mai 2023, that she try this out: await browserInstance.refresh(); await ui5Service.injectUI5(browserInstance); But this do not working because of some error.

"some error" won't help much here unfortunately...what's the error (message) exactly?
