### ISSUE TITLE
File upload in wdi5

### ISSUE THREAD

**Issue by Rchn1907** [ui5-community/wdi5#472]
Hi everyone,
I have an App with an sap.m.upload.UploadSet in it and I want to test it now.
I tried a lot of things but could not attach a File, fire an event and test the upload,
My SAPUI5-Tree looks like this:
![image](https://github.com/ui5-community/wdi5/assets/116603031/996d526e-4aa3-4d36-be9a-5013ecb9c3f5)
Would be great if you can help me

**Comment by vobu** [comment]
Hi, there's a recipe for that in the -well- "recipe" section of the docs: https://ui5-community.github.io/wdi5/#/recipes?id=conducting-a-file-upload
Also, I don't see this being a real issue, but more of a support request (that's why I'm closing this). You might be happy to learn that the steering committee agreed to open up `wdi5` for vendors offering commercial support for the tool - stay tuned! (note that `wdi5` will forever stay Open Source, with a [dual license: derived 🍺 -ware and Apache 2.0](https://github.com/ui5-community/wdi5/blob/main/LICENSE))
For community support, please post in https://answers.sap.com/questions/ask.html (and tag it with a user tag `wdi5`) and hop over [to the `wdi5` Slack channel ](https://ui5-slack-invite.cfapps.eu10.hana.ondemand.com/).
