### ISSUE TITLE
Slow test execution with SAP Fiori Elements test library

### ISSUE THREAD

**Issue by MiBe17** [ui5-community/wdi5#558]
**Describe the bug**
We use the Fiori Elements Facade to test our FE app extensively and experience heavy performance problems in some cases. These problems occur mostly if we perform an action or an assertion on a control that exists multiple times on the current screen. 
Example:

```shell
await FioriElementsFacade.execute((Given, When) => {
    When.onTheDocumentsList.onTable().iPressRow({
        "Title": "some title"
    });
});
```

The statement above takes a really long time to execute, if we have a lot of elements in the table. I think this happens since the Fiori Elements Facade converts each and every list element to the respective UI5 representation before finding and clicking the one with the correct title. The same is true if we e.g. try to click a button, when there are a lot of other sap.m.Button elements on the same page.

In plain wdi5, we could just use the [get shorthand conveniences](https://ui5-community.github.io/wdi5/#/usage?id=getshorthand-conveniences) to avoid the conversion to UI5 objects in order to improve performance. As far as I know, we do not have this option when using the Fiori Elements Facade.

Do you have any suggestions on how to improve performance in such cases?
Regards!

**Comment by vobu** [comment]
hi, thanks for checking in on this - the way we utilise the OData v4 test library from UI5 is by a simple wrapper, without adding any extra test library code. Thus the naming "Facade" in the "Fiori Elements Facade" aka "OData v4 test library Facade".
Would you mind helping us to get to the root cause of this?
A good starting point 
- for the Node.js-scope https://github.com/ui5-community/wdi5/blob/fe88546e2b0ef5bec06f32d03f19003a41bc1c09/src/lib/wdi5-fe.ts#L103
   → this is where all function calls are assembled to be passed to the browser
- for client-side debugging in the browser could be https://github.com/ui5-community/wdi5/blob/fe88546e2b0ef5bec06f32d03f19003a41bc1c09/client-side-js/testLibrary.cjs#L86
   → this is where all the OPA calls are executed in the browser-scope

**Comment by vobu** [comment]
even though there has been no comment, posting here to say that we're actively looking into it, combined with #557

**Comment by vobu** [comment]
we're actively looking into reducing complexity in the client-side serialization → @sebbi08 is on that and it might help here too.
background: we just recently discovered that there's > 100 MB(!) on "context" objects on any given Fiori Elements UI control...

**Comment by vobu** [comment]
hey @MiBe17, did the latest [improvements](https://github.com/ui5-community/wdi5/commit/f2843c10a130ec5c05837125ba94cfec32d532c0) help to speed things up for you?
