### ISSUE TITLE
What about self-contained applications ?

### ISSUE THREAD

**Issue by ArnaudBuchholz** [ui5-community/wdi5#562]
**Describe the bug**
@ui5/cli offers the possibility to bundle the app in a self-contained way, meaning UI5 resources are reduced to the strict minimum to run the app.
If this app is deployed, will WDI5 be able to work with it as it does not contain the [UI5 Test (RecordReplay) APIs](https://ui5.sap.com/#/api/sap.ui.test) ?

**To Reproduce**
⛔

**Expected behavior**
Either it works or it does not, but if not, it has to be clearly specified in the documentation.

**Logs/Console Output**
⛔

```shell
$> ...
```

**Screenshots**
⛔

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: assuming latest
- `UI5` version: supported one
- `wdio`-version (output of `wdio --version`): assuming latest
- `node`-version (output of `node --version`): assuming lts
- OS: is it relevant ?
- Browser + Version : assuming a supported one

**Additional context**
This is a theoretical question, it would require a bit to reproduce it but if the matter is considered relevant, I can try to build one.

**Comment by vobu** [comment]
`wdi5` definitely needs the RecordReplay API - so self-contained builds that do not hold https://ui5.sap.com/#/api/sap.ui.test.RecordReplay as a dependency (e.g. in `Component.(j|t)s`) included (`sap.ui.define`|`import`) will not work with `wdi5`.
So yes, definitely up for being documented - PR pretty please, @ArnaudBuchholz? 😸 
At the same time, I'm going to put revamping the bootstrap process on the [roadmap](https://github.com/orgs/ui5-community/projects/2) - this issue is a good starting point for it 👍

**Comment by dominikfeininger** [comment]
Could the required `sap.ui.test.*` code be injected before test?

**Comment by ArnaudBuchholz** [comment]
> Could the required `sap.ui.test.*` code be injected before test?

The problem is that self-contained application might come with any flavor of UI5... How do we know which version of the library should be used...
